server:
    port: 8080
    servlet:
        context-path: /identity

spring:
    application:
        name: identity-service
    datasource:
        url:  ${DBMS_CONNECTION_URL:jdbc:sqlserver://localhost:1433;databaseName=Identity;encrypt=true;trustServerCertificate=true}
        username: ${DBMS_CONNECTION_USERNAME:sa}
        password: ${DBMS_CONNECTION_PASSWORD:123456789}
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jpa:
        database-platform: org.hibernate.dialect.SQLServerDialect
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        defer-datasource-initialization: true
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${CLIENT_ID:129354124634-jt4im8o5p7a0co5b938q6qgblf6vfsg2.apps.googleusercontent.com}
                        client-secret: ${CLIENT_SECRET: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}
                        redirect-uri: ${REDIRECT_URI:http://localhost:8080/identity/login/oauth2/code/google}
                        user-info-uri: ${USER_INFO_URI:https://www.googleapis.com/oauth2/v3/userinfo}
                        scope:
                            - openid
                            - profile
                            - email
                provider:
                    google:
                        authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
                        token-uri: https://oauth2.googleapis.com/token
                        user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
    redis:
        host: ${REDIS_HOST:localhost}
        port: ${REDIS_PORT:6379}

jwt:
    signerKey: ${SIGNER_KEY:t47lu0FHQY5XHLeC5uViwOtAuzBT0cpkFdDgWZfrRHF1Y2e6XB2oVVRHzKyb/9Fa}
    refreshable-duration: 7200 # in second
    valid-duration: 3600 # in second
app:
    services:
        profile: ${PROFILE_SERVICE_URL:http://localhost:8081/profile}
    frontend:
        url: ${FRONTEND_URL:http://localhost:4200}

