server:
    port: 8080
    servlet:
        context-path: /identity

spring:
    application:
        name: identity-service
    datasource:
        url: jdbc:sqlserver://localhost:1437;databaseName=Identity;encrypt=true;trustServerCertificate=true
        username: sa
        password: YourStrong!Passw0rd
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jpa:
        database-platform: org.hibernate.dialect.SQLServerDialect
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        defer-datasource-initialization: true
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 129354124634-jt4im8o5p7a0co5b938q6qgblf6vfsg2.apps.googleusercontent.com
                        client-secret: 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
                        redirect-uri: "http://localhost:8080/identity/login/oauth2/code/google"
                        user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
                        scope:
                            - openid
                            - profile
                            - email
                provider:
                    google:
                        authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
                        token-uri: https://oauth2.googleapis.com/token
                        user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
    redis:
        host: localhost
        port: 6379

jwt:
    signerKey: "t47lu0FHQY5XHLeC5uViwOtAuzBT0cpkFdDgWZfrRHF1Y2e6XB2oVVRHzKyb/9Fa"
    refreshable-duration: 7200 # in second
    valid-duration: 3600 # in second
app:
    services:
        profile: "http://localhost:8081/profile"
    frontend:
        url: http://localhost:4200

eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka/
    instance:
        preferIpAddress: true
