apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          image: phuongnbp/search-service:0.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          env:
            - name: KAFKA_CONNECTION
              value: kafka:9092
            - name: ELASTICSEARCH
              value: http://elasticsearch:9200
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
spec:
  selector:
    app: search-service
  ports:
    - port: 8084
      targetPort: 8084
  type: ClusterIP