spring:
  application:
    name: comment-service
  datasource:
    url: jdbc:sqlserver://localhost:1440;databaseName=Comment;encrypt=true;trustServerCertificate=true
    username: sa
    password: YourStrong!Passw0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        acks: -1
        retries: 1 #gửi lại nếu lỗi
        # properties: 
        #     enable.idempotence: true
        #     max.
app:
    services:
      music: http://localhost:8082/music-service

server:
  port: 8086
  servlet:
    context-path: /comment-service