spring:
  application:
    name: comment-service
  datasource:
    url: ${DBMS_CONNECTION_URL:jdbc:sqlserver://sql-server-for-comment:1433;databaseName=Comment;encrypt=true;trustServerCertificate=true}
    username: ${DBMS_CONNECTION_USERNAME:sa}
    password: ${DBMS_CONNECTION_PASSWORD:YourStrong!Passw0rd}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true
  kafka:
    bootstrap-servers: ${KAFKA_CONNECTION:kafka:9092}
    producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        acks: -1
        retries: 1 #gửi lại nếu lỗi
        # properties: 
        #     enable.idempotence: true
        #     max.
app:
    services:
      music:  ${MUSIC_SERVICE_URL:http://music-service:8082/music-service}
      profile: ${PROFILE_SERVICE_URL:http://profile-service:8081/profile}
server:
  port: 8086
  servlet:
    context-path: /comment-service