spring:
  application:
    name: comment-service
  datasource:
    url: jdbc:sqlserver://localhost:1440;databaseName=Comment;encrypt=true;trustServerCertificate=true
    username: sa
    password: YourStrong!Passw0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true
app:
  services:

server:
  port: 8086
  servlet:
    context-path: /comment-service