server:
  port: 8888
app:
  api-prefix: /api
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=1
        - id: profile
          uri: lb://profile-service
          predicates:
            - Path=${app.api-prefix}/profile/**
          filters:
            - StripPrefix=1
        - id: music-service
          uri: lb://music-service
          predicates:
            - Path=${app.api-prefix}/music-service/**
          filters:
            - StripPrefix=1

        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=${app.api-prefix}/file-service/**
          filters:
            - StripPrefix=1
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=${app.api-prefix}/search-service/**
          filters:
            - StripPrefix=1
        - id: user-library-service
          uri: lb://user-library-service
          predicates:
            - Path=${app.api-prefix}/user-library/**
          filters:
            - StripPrefix=1
        - id: comment-service
          uri: http://localhost:8086
          predicates:
            - Path=${app.api-prefix}/comment-service/**
          filters:
            - StripPrefix=1

        - id: notification-service
          uri: http://localhost:8087
          predicates:
            - Path=${app.api-prefix}/notification-service/**
          filters:
            - StripPrefix=1
        - id: admin-service
          uri: http://localhost:8088
          predicates:
            - Path=${app.api-prefix}/admin-service/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      default-zone:
        http://localhost:8761/eureka/