server:
  port: 8085
  servlet:
    context-path: /user-library
spring:
  application:
    name: user-library-service
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=UserLibrary;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123456789
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true
app:
    services:
        file: http://localhost:8083/file-service