server:
  port: 8085
  servlet:
    context-path: /user-library
spring:
  application:
    name: user-library-service
  datasource:
    url: jdbc:sqlserver://localhost:1432;databaseName=UserLibrary;encrypt=true;trustServerCertificate=true
    username: sa
    password: YourStrong!Passw0rd
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB
app:
    services:
        file: http://localhost:8083/file-service
        music: http://localhost:8082/music-service

track:
  related:
    limit: 20
history:
  top-recentlyplayed:
    limit: 30
  size-of-list: 10

eureka:
  client:
    service-url:
      default-zone:
        http://localhost:8761/eureka/
  instance:
    preferIpAddress: true