server:
  port: 8085
  servlet:
    context-path: /user-library
spring:
  application:
    name: user-library-service
  datasource:
    url:     ${DBMS_CONNECTION_URL:jdbc:sqlserver://localhost:1433;databaseName=UserLibrary;encrypt=true;trustServerCertificate=true}
    username: ${DBMS_CONNECTION_USERNAME:sa}
    password: ${DBMS_CONNECTION_PASSWORD:123456789}
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB
  kafka:
    bootstrap-servers: ${KAFKA_CONNECTION:localhost:9094}
    producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        acks: -1
        retries: 1 #gửi lại nếu lỗi
        # properties: 
        #     enable.idempotence: true
        #     max.
app:
    services:
        file:  ${FILE_SERVICE_URL:http://localhost:8083/file-service}
        music:  ${MUSIC_SERVICE_URL:http://localhost:8082/music-service}
        comment: ${COMMENT_SERVICE_URL:http://localhost:8086/comment-service}
        profile: ${PROFILE_SERVICE_URL:http://localhost:8081/profile}


track:
  related:
    limit: 20
history:
  top-recentlyplayed:
    limit: 30
  size-of-list: 10