apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  selector:
    app: admin-service
  ports:
    - port: 8088
      targetPort: 8088

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
        - name: admin-service
          image: phuongnbp/admin-service:0.0.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8088
          env:
            - name: COMMENT_SERVICE_URL
              value: http://comment-service:8086/comment-service
            - name: USERLIB_SERVICE_URL
              value: http://user-library-service:8085/user-library
