apiVersion: v1
kind: Service
metadata:
  name: comment-service
spec:
  type: LoadBalancer
  selector:
    app: comment-service
  ports:
    - port: 8086
      targetPort: 8086

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment-service
  template:
    metadata:
      labels:
        app: comment-service
    spec:
      containers:
        - name: comment-service
          image: phuongnbp/comment-service:0.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
          env:
          - name: DBMS_CONNECTION_URL
            value: jdbc:sqlserver://mssql-service:1433;databaseName=Comment;encrypt=true;trustServerCertificate=true
          - name: DBMS_CONNECTION_USERNAME
            value: sa
          - name: DBMS_CONNECTION_PASSWORD
            value: YourStrong!Passw0rd
          - name: MUSIC_SERVICE_URL
            value: http://music-service:8082/music-service
          - name: KAFKA_CONNECTION
            value: kafka:9092

