apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: upload-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi       # kích thước bạn cần
  storageClassName: standard   # tên StorageClass trên minikube hoặc cluster bạn đang dùng
---
apiVersion: v1
kind: Service
metadata:
  name: file-service
spec:
  type: LoadBalancer
  selector:
    app: file-service
  ports:
    - port: 8083
      targetPort: 8083

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
    spec:
      containers:
        - name: file-service
          image: phuongnbp/file-service:0.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: DBMS_CONNECTION_URL
              value: jdbc:sqlserver://mssql-service:1433;databaseName=File;encrypt=true;trustServerCertificate=true
            - name: DBMS_CONNECTION_USERNAME
              value: sa
            - name: DBMS_CONNECTION_PASSWORD
              value: YourStrong!Passw0rd
          volumeMounts:
            - name: upload-storage
              mountPath: /app/uploads
      volumes:
        - name: upload-storage
          persistentVolumeClaim:
            claimName: upload-pvc
          
