apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  type: LoadBalancer
  selector:
    app: identity-service
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
        - name: identity-service
          image: phuongnbp/identity-service:0.0.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DBMS_CONNECTION_URL
              value: jdbc:sqlserver://mssql-service:1433;databaseName=Identity;encrypt=true;trustServerCertificate=true
            - name: DBMS_CONNECTION_USERNAME
              value: sa
            - name: DBMS_CONNECTION_PASSWORD
              value: YourStrong!Passw0rd
            - name: PROFILE_SERVICE_URL
              value: http://profile-service:8081/profile
            - name: NOTIFICATION_SERVICE_URL
              value: http://notification-service:8087/notification-service
            - name: FRONTEND_URL
              value: http://localhost:4200
            - name: REDIS_HOST
              value: redis
            - name: REDIRECT_URI
              value: http://localhost:8080/identity/login/oauth2/code/google
