apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-notification-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-notification
spec:
  selector:
    app: mongodb-notification
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-notification
  template:
    metadata:
      labels:
        app: mongodb-notification
    spec:
      containers:
        - name: mongodb
          image: bitnami/mongodb:8.0.5-debian-12-r0
          ports:
            - containerPort: 27017
          env:
            - name: MONGODB_ROOT_USER
              value: "root"
            - name: MONGODB_ROOT_PASSWORD
              value: "123"
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongodb-notification-pvc
