server:
    port: 8081
    servlet:
        context-path: /profile

spring:
    # datasource:
    #   url: "jdbc:mysql://localhost:3306/profile_service"
    #   username: "root"
    #   password: "sa"
    # jpa:
    #   hibernate:
    #     ddl-auto: update
    #   show-sql: true
    kafka:
        bootstrap-servers: localhost:9094
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            acks: -1
            retries: 1 #gửi lại nếu lỗi
    application:
        name: profile-service
    datasource:
        url: jdbc:sqlserver://localhost:1433;databaseName=Profile;encrypt=true;trustServerCertificate=true
        username: sa
        password: 123456789
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jpa:
        database-platform: org.hibernate.dialect.SQLServerDialect
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        defer-datasource-initialization: true
    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 50MB

app:
    services:
        file: "http://localhost:8083/file-service"
