server:
    port: 8081
    servlet:
        context-path: /profile

spring:
    kafka:
        bootstrap-servers:  ${KAFKA_CONNECTION:kafka:9092}
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            acks: -1
            retries: 1 #gửi lại nếu lỗi
    application:
        name: profile-service
    datasource:
        url: ${DBMS_CONNECTION_URL:jdbc:sqlserver://sql-server-for-profile:1433;databaseName=Profile;encrypt=true;trustServerCertificate=true}
        username: ${DBMS_CONNECTION_USERNAME:sa}
        password: ${DBMS_CONNECTION_PASSWORD:YourStrong!Passw0rd}
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jpa:
        database-platform: org.hibernate.dialect.SQLServerDialect
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        defer-datasource-initialization: true
    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 50MB

app:
    services:
        file:  ${FILE_SERVICE_URL:http://file-service:8083/file-service}
