server:
  port: 8081
  servlet:
    context-path: /profile
#spring:
#  neo4j:
#    uri: bolt://localhost:7687
#    authentication:
#      username: neo4j
#      password: 12345678

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/profile_service"
    username: "root"
    password: "sa"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


#spring:
#  datasource:
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: "jdbc:sqlserver://LAPTOP-3KF7N80A\\SQLEXPRESS:1433;databaseName=identity_service;encrypt=true;trustServerCertificate=true"
#    username: "sa"
#    password: "123456789"
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true



app:
  services:
    file: "http://localhost:8082/file-service"