server:
  port: 8081
  servlet:
    context-path: /profile
#spring:
#  neo4j:
#    uri: bolt://localhost:7687
#    authentication:
#      username: neo4j
#      password: 12345678

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/profile_service"
    username: "root"
    password: "sa"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true