spring:
  application:
    name: admin-service
server:
  port: 8088
  servlet:
    context-path: /admin-service

app:
    services:
      comment: http://localhost:8086/comment-service
      userlib: http://localhost:8085/user-library
eureka:
  client:
    service-url:
      default-zone:
        http://localhost:8761/eureka/
  instance:
    preferIpAddress: true