spring:
    application:
        name: music-service
    datasource:
        url: ${DBMS_CONNECTION_URL:jdbc:sqlserver://sql-server-for-music:1433;databaseName=Music;encrypt=true;trustServerCertificate=true}
        username: ${DBMS_CONNECTION_USERNAME:sa}
        password: ${DBMS_CONNECTION_PASSWORD:YourStrong!Passw0rd}
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jpa:
        database-platform: org.hibernate.dialect.SQLServerDialect
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        defer-datasource-initialization: true
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 200MB
    kafka:
        bootstrap-servers: ${KAFKA_CONNECTION:kafka:9092}
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            acks: -1
            retries: 1 #gửi lại nếu lỗi
            # properties: 
            #     enable.idempotence: true
            #     max.
app:
    services:
        file:  ${FILE_SERVICE_URL:http://file-service:8083/file-service}
        comment: ${COMMENT_SERVICE_URL:http://comment-service:8086/comment-service}
        user-library: ${USERLIB_SERVICE_URL:http://user-library-service:8085/user-library}
server:
    port: 8082
    servlet:
        context-path: /music-service
