spring:
  application:
    name: music-service
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=Music;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123456789
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true
app:
    services:
        file: http://localhost:8083/file-service

server:
  port: 8082
  servlet:
    context-path: /music-service